### ISSUE TITLE
special instruction for GameplayCues in a GameFeature plugin

### ISSUE THREAD

**Issue by braheem** [x157/x157.github.io#2]
Not sure if you added something for this already.

When working on a gameplay ability, it's likely someone will want to add VFX/sound  to their gameplay ability and they will probably use a GameplayCue. Copying what epic did in shootercore for gameplaycues is simple enough, but there is one step that might be very useful for you to include in your guides to help others who might run into this problem.

Assuming you have gameplaycues stored in `XistGame Content/GameplayCues`, you'll want to add an entry in `Actions `for `XistGame.uasset`:
![Cue](https://user-images.githubusercontent.com/4989986/182027208-ee3675fd-6d4e-42eb-8f0d-c216395c620c.PNG)

My gameplaycue worked fine for a while until it didn't and this was the step I added to fix it. ShooterCore has this as well in `ShooterCore.uasset`.

If this is not done, blueprints will simply ignore any nodes executing gameplaycues and nothing will be written to the log (atleast in my experience).

**Comment by x157** [comment]
Thanks very much for the feedback!

That path should probably be set to `/XistGame/GameplayCues` so that it's contained in the plugin rather than in the Lyra-owned directory.

I'll need to do a little work to get that into the documentation since it's kind of a new section in that tutorial flow.  Will work on it!

**Comment by x157** [comment]
Done!

Added https://x157.github.io/UE5/LyraStarterGame/Setup/GameFeatureData-AddGameplayCuePath

Linked it into the new project setup process, right after configuring Asset Manager.

Thanks again!  👍
