### ISSUE TITLE
Anim BP customizations

### ISSUE THREAD

**Issue by tonymckendry** [x157/x157.github.io#4]
Hey there - huge appreciation for your Lyra guide! 
I was wondering how you handle customizations to the base AnimBPs (like the ones seen in [this video - timestamped)](https://youtu.be/oQvWl-bi8pI?t=1640)? 
I initially tried to just make a copy of the Mannequin_Base and LinkedLayers folder in my Plugin Folder but it was certainly not plug-n-play when I tried to use it. Is this the right approach? Is there a better way? 
Per your guide, I'm trying not to alter the original Lyra file if possible.

**Comment by x157** [comment]
I must admit that in the case of the animations, I just modified the 2 Lyra files directly.  Those modifications are very clearly bugs that I hope Epic will fix in the future.  I can't really imagine Epic making changes to those files without fixing those bugs.

That being said, if you want to be really super safe about it, then you would want to `Advanced Copy` for example `ABP_UnarmedAnimLayers` (and the `_Feminine` one) into your own GameFeatures plugin.

There are MANY, MANY pieces of that animation that are all binary assets.  Initially I'd try ONLY advanced copying the ones that you will change.  However, that may not work.

In the worst case scenario, you can advanced copy those BPs and ALL of their dependencies into your project, and then only change the 2 that you need to change.

Again in this case though, I just modified the base Lyra asset, and made a note for myself that if Epic ever changes these files in the future to make sure they fixed the bug in addition to whatever other changes they make.

**Comment by tonymckendry** [comment]
@x157 I kinda thought it was looking that way - thanks for the response and all you do!
